### ISSUE TITLE
读取文件的时候报错

### ISSUE THREAD

**Issue by huanzhang** [huacnlee/carrierwave-aliyun#25]
[36] pry(main)> maf.file.read
RestClient::Forbidden: 403 Forbidden
from /Users/zhanghuan/.rvm/gems/ruby-2.1.5@kt-mfame/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!'

可以上传和删除文件，就是读取文件内容时候报错。

**Comment by huacnlee** [comment]
403 是权限的问题，可能是 apiKey 和 secrect 不对

**Comment by huanzhang** [comment]
@huacnlee 同样的access_id和access_key，可以上传和删除。

**Comment by huanzhang** [comment]
@huacnlee 下载私有文件的时候，sign这个方法有可能不对

**Comment by huanzhang** [comment]
@huacnlee 
我找到问题所在了：
在gemfile里引入gem 'carrierwave-aliyun', github: 'huacnlee/carrierwave-aliyun'而不仅仅是gem 'carrierwave-aliyun'
我想你是否应该在rubygems更新下gem了
