### ISSUE TITLE
上传时怎样设置Head的Content-Disposition参数

### ISSUE THREAD

**Issue by wangrui438** [huacnlee/carrierwave-aliyun#29]
上传文件时的文件名是随机产生的，但是下载时需要显示原始文件名，查看[aliyun_oss接口](https://github.com/carrierwaveuploader/carrierwave/wiki/how-to:-create-random-and-unique-filenames-for-all-versioned-files#unique-filenames)发现，可以通过在**Head**中指定**Content-Disposition**参数实现，请问怎样实现？

**Comment by huacnlee** [comment]
上传文件名不是随机的，你可以正确的设置文件名，请正确使用 carrierwave 的 filename 覆盖功能，可以自定义文件名的。

**Comment by wangrui438** [comment]
可能是我没有描述清楚，我的上传文件名是通过[这种方式](https://github.com/carrierwaveuploader/carrierwave/wiki/how-to:-create-random-and-unique-filenames-for-all-versioned-files#random-filenames)实现，但是从阿里云oss上下载文件时又不希望给用户显示uuid的文件名而是原始上传的文件名，因此才有了上传时需要设置**Content-Disposition**参数的需求。

**Comment by huacnlee** [comment]
就算实现这个，按 carrierwave 的接口方式，你也没地方传值的。

你这个需求简单的处理方式就是把 filename 换成你需要的目录/文件名，浏览器下载只会保留文件名部分

**Comment by huacnlee** [comment]
新版本可以实现了

```rb
# app/uploaders/attachment_uploader.rb
class AttachmentUploader < CarrierWave::Uploader::Base
  def content_disposition
    # 非图片文件，给 content_disposition
    unless file.extension.downcase.in?(%w(jpg jpeg gif png svg))
      "attachment;filename=#{file.original_filename}"
    end
  end
end
```
