### ISSUE TITLE
重载filename有问题

### ISSUE THREAD

**Issue by yijiasu** [huacnlee/carrierwave-aliyun#30]
重载了filename方法：

  def filename
    "#{DateTime.now().strftime("%Y%m%d")}-#{SecureRandom.hex.first(12)}" if original_filename
  end

然后最终上传到阿里云的文件名和保存到数据库的是完全的两个名称。并不一样

**Comment by huacnlee** [comment]
https://github.com/ruby-china/ruby-china/blob/master/app/uploaders/photo_uploader.rb#L5

**Comment by huacnlee** [comment]
```rb
@name ||= Digest::MD5.hexdigest(current_path)
```

确保生成的文件名存到实例变量里面，在 Request 周期一直存在
