### ISSUE TITLE
设置aliyun_private_read=true获取到的URL签名不正确

### ISSUE THREAD

**Issue by wangrui438** [huacnlee/carrierwave-aliyun#35]
访问获取到的URL，获得如下信息：`The request signature we calculated does not match the signature you provided. Check your key and signing method.`
配置参数都没有问题

**Comment by huacnlee** [comment]
已经找到原因了，你可以暂时先在 Gemfile 里面依赖这个来解决:

```rb
gem 'aliyun-oss-sdk', github: 'huacnlee/aliyun-oss-ruby-sdk', branch: 'fix/signature-encode'
```

等那边合并以后，我会发布新版本

**Comment by wangrui438** [comment]
ok了，华顺的速度真是杠杠的

**Comment by huacnlee** [comment]
Fixed 0.4.3
