### ISSUE TITLE
判断是否文件存

### ISSUE THREAD

**Issue by liuliang** [huacnlee/carrierwave-aliyun#37]
比如有的时候我们判断用户头像是否存在，之前经常用 user.avatar?, 现在总是返回 false

**Comment by huacnlee** [comment]
这个和 carrierwave-aliyun 没有关系，`user.avatar?` 实际上是检查 `users` 表里面 `avatar` 字段是否有内容，而不是检查远程的图片 URL 是否存在

**Comment by liuliang** [comment]
> User id: 3, avatar: "c80afd1f460b10baad9433d264676ccd.png"
> User.find(3).avatar? => false
不知道我理解的是否正确，检查了下数据库这个字段里面有值

**Comment by liuliang** [comment]
> 2.3.1 :017 > User.find(3).method(:avatar?).source_location
  User Load (0.5ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 3 LIMIT 1
 => ["~/.rvm/gems/ruby-2.3.1/gems/carrierwave-0.11.2/lib/carrierwave/mount.rb", 166]

**Comment by huacnlee** [comment]
好像是 carrierwave-aliyun 少实现了什么函数。我看其他 Storage 是有个 exists? 方法检查远程，但尝试给  carrierwave-aliyun 加上，没有效果。

你可以先用 `user[:avatar]`

**Comment by wanxsb** [comment]
@huacnlee 
https://github.com/diandanbao/carrierwave-aliyun/commit/c7d5afae265d80b37979dba2b2adbb94ceb39a43

AliyunFile的initialize没有继承SanitizeFile，或许需要overwrite empty?

**Comment by mountriv99** [comment]
我也遇到這個問題
