### ISSUE TITLE
Aliyun::Oss改为Aliyun::OSS了吧

### ISSUE THREAD

**Issue by michael-ji0406** [huacnlee/carrierwave-aliyun#38]
lib/carrierwave/aliyun/bucket.rb 文件`oss_upload_client`中的`Aliyun::Oss`会报错，改成｀Aliyun::OSS`就可以了

**Comment by michael-ji0406** [comment]
因为我项目中有aliyun-oss-sdk和aliyun-sdk， 所以搞混了

**Comment by fwshun8023** [comment]
请问你现在项目aliyun-oss-sdk和aliyun-sdk怎么共用的？还是说只有了其中一个了
