### ISSUE TITLE
为什么不使用OSS官方文档中提供的aliyun-oss-ruby-sdk呢？

### ISSUE THREAD

**Issue by fwshun8023** [huacnlee/carrierwave-aliyun#40]
我看官方文档提供的SDK是 https://github.com/aliyun/aliyun-oss-ruby-sdk ，但是这里使用的是 https://github.com/aliyun-beta/aliyun-oss-ruby-sdk 
这样很多人开始按官方文档用了的话，现在升级carrierwave-aliyun不是会require同样的名字而不再能升级。
求解答

**Comment by huacnlee** [comment]
https://github.com/aliyun-beta/aliyun-oss-ruby-sdk 也是官方的
