### ISSUE TITLE
文件名如果是西班牙语的带accent的字符的话，上传的文件无法下载

### ISSUE THREAD

**Issue by gogo52cn** [huacnlee/carrierwave-aliyun#44]
文件名如果是西班牙语的带accent的字符的话，上传的文件无法下载。

示例文件如下：

[Revisión  Corazón 50ml.xlsx](https://github.com/huacnlee/carrierwave-aliyun/files/803970/Revision.Corazon.50ml.xlsx)

**Comment by gogo52cn** [comment]
请求文件得到以下的结果：

<img width="1337" alt="screen shot 2017-02-27 at 10 52 36 pm" src="https://cloud.githubusercontent.com/assets/5362705/23365837/8972d4aa-fd3f-11e6-9b2b-f59009c35191.png">

**Comment by huacnlee** [comment]
不要将 URL 文件名用特别的字符，如果你期望下载的时候获得原始的文件名，你应该用：

```rb
# app/uploaders/attachment_uploader.rb
class AttachmentUploader < CarrierWave::Uploader::Base
  def content_disposition
    # 非图片文件，给 content_disposition
    unless file.extension.downcase.in?(%w(jpg jpeg gif png svg))
      "attachment;filename=#{file.original_filename}"
    end
  end
end
```

详见 README 末尾的说明：

https://github.com/huacnlee/carrierwave-aliyun#增对文件设置-content-disposition
