### ISSUE TITLE
删除文件后，aliyun oss的文件还在云端

### ISSUE THREAD

**Issue by zhangle** [huacnlee/carrierwave-aliyun#55]
是不是老版本的aliyun oss sdk导致？

**Comment by wanxsb** [comment]
@huacnlee
diandanbao/carrierwave-aliyun@c7d5afa

暂时可以
````
gem 'ckeditor', github: 'diandanbao/ckeditor'
````

**Comment by huacnlee** [comment]
https://github.com/huacnlee/carrierwave-aliyun/blob/main/test/bucket_test.rb#L52

有测试的，现在应该没有这个问题了
