### ISSUE TITLE
如果设置aliyun_private_read = true，自定义host失效

### ISSUE THREAD

**Issue by wuyuedefeng** [huacnlee/carrierwave-aliyun#57]
求助，如果设置aliyun_private_read = true，自定义aliyun_host会不起作用，仍然返回aliyun本身的地址

这里也有人遇到了相同的问题
`https://ruby-china.org/topics/34517`

可以修复下吗

**Comment by huacnlee** [comment]
https://github.com/huacnlee/carrierwave-aliyun/blob/master/lib/carrierwave/aliyun/bucket.rb#L103

可能需要这里替换一下 host
