### ISSUE TITLE
carrierwave 2.0.0 support

### ISSUE THREAD

**Issue by Eric-Guo** [huacnlee/carrierwave-aliyun#64]
After upgrade to [carrierwave 2.0.0](https://github.com/carrierwaveuploader/carrierwave/blob/master/CHANGELOG.md#200---2019-08-18), meet below errors from log:

```log
NotImplementedError (Need to implement #cache! if you want to use CarrierWave::Storage::Aliyun as a cache storage.):
```

version 1.3.1 works well.

**Comment by huacnlee** [comment]
1.1.0
