### ISSUE TITLE
carrierwave 2.0 兼容有问题

### ISSUE THREAD

**Issue by pidanjun** [huacnlee/carrierwave-aliyun#68]
`carrierwave-aliyun (1.1.0)` 搭配使用 `gem 'carrierwave', '~> 2.0'`

出现两个严重问题。

## 1、新增数据的时候

```ruby
  def store_dir
    "#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end
```

这里使用 `model.id`，会直接是 `空`，拿不到数据

## 2、验证失败，照样上传

如果表单验证失败，例如文章标题没有填写之类的。
在阿里OSS中，照样能看到上传了图片上去了。

## 一些尝试
- 测试过，使用  `storage :file`，并没有这些问题发生
- `gem 'carrierwave', '~> 1.0'`，改为 `1.0`版本后，这些问题也消失了，一切正常了。
于是我现在使用的是 `carrierwave 1.0` 搭配 `carrierwave-aliyun 1.1.0`

**Comment by huacnlee** [comment]
有可能是 `cache!` 函数实现了存储导致的，CarrierWave 2.0 的 API 改动我还没习惯，等我再仔细看看
