### ISSUE TITLE
carrierwave 2.0 兼容依然有问题

### ISSUE THREAD

**Issue by clwy-cn** [huacnlee/carrierwave-aliyun#70]
这次测试，新增的时候，能获取到 `#{model.id}` 了。但还是有个小的问题：

当验证失败的时候，例如文章标题没有填写，依然会上传文件到oss

![image](https://user-images.githubusercontent.com/57120683/68646161-4b2fbc00-0555-11ea-9f52-48b7fd744951.png)

切换到 `carrierwave 1.3.1`， 问题消失

**Comment by pidanjun** [comment]
另外针对缩略图，能否多加一个方法进去？

现在使用缩略图，需要 .url(thumb: '?x-oss-process=image/resize,h_100') 或者  .url(thumb: '!avatar') 。
为了简便操作，最好就是能直接使用 `.url(:avatar)` 这种写法

于是就只能自己搞个 `url` 方法

```ruby
  def url(version = nil)
    url_path = super({})
    return url_path if version.blank?
    "#{url_path}!#{version}"
  end
```

能否考虑直接集成到 gem 里面去？方便用户能直接用 `.url(:avatar)`  这种写法

**Comment by huacnlee** [comment]
tmp 文件是 carrierwave 的 cache 机制

url 那个方法你可以自己在 `BaseUploader` 里面实现

**Comment by huacnlee** [comment]
tmp 文件夹里面的文件会有清理机制，目前这部分我没搞明白，不知为何 carrierwave 需要它

**Comment by pidanjun** [comment]
tmp是很奇怪，如果上传成功后，tmp文件会自己清理掉。
如果用户提交失败，页面关闭，tmp文件会一直保留在oss里面。
这会导致oss上，tmp里文件越来越多了。

url我是参照homeland的代码自己实现了，只是觉得如果能集成到gem里，就更加方便好用一些了。只是一个小建议

**Comment by huacnlee** [comment]
Version 1.2.2 has been fixed this issue.
