### ISSUE TITLE
当传了一个中文名的文件，报The specified key does not exist错误

### ISSUE THREAD

**Issue by clwy-ito** [huacnlee/carrierwave-aliyun#79]
英文文件名是完全正常，只有中文名的文件上传出错。

![image](https://user-images.githubusercontent.com/76093713/104724952-5e977200-576c-11eb-80db-8cbcbd9c7798.png)

环境： 
- ruby 3.0
- rails 6.1
- carrierwave 2.1.0
- carrierwave-aliyun 1.2.1

**Comment by clwy-ito** [comment]
我建了一个非常基础的代码，只有最基本的上传功能

https://github.com/clwy-ito/demo

在建好数据库后
```
rails db:create
rails db:migrate
```

请修改`config/initializers/carrierwave.rb`为正确的阿里云oss信息后测试

访问地址 https://localhost:3000/articles

![image](https://user-images.githubusercontent.com/76093713/104725756-7d4a3880-576d-11eb-980c-55d3a185c1b8.png)

**Comment by huacnlee** [comment]
https://github.com/ruby-china/homeland/blob/main/app/uploaders/photo_uploader.rb#L5

**Comment by clwy-ito** [comment]
这个我试过的，依然还是会报以上错误，我已经提交到https://github.com/clwy-ito/demo。

```ruby
def filename
    if super.present?
      @name ||= SecureRandom.uuid
      "#{Time.now.year}/#{@name}.#{file.extension.downcase}"
    end
end
```

![image](https://user-images.githubusercontent.com/76093713/104861895-8a814600-596c-11eb-9475-72528e3bdc6f.png)


![image](https://user-images.githubusercontent.com/76093713/104861890-848b6500-596c-11eb-9aaf-61005dfee8cd.png)


除此外，我还尝试过多种方案：

- 直接用carrierwave，而不用carrierwave-aliyun，上传中文名文件，正常上传。
- 使用 ruby 2.7.2 + rails 6.1 + carrierwave 1 + carrierwave-aliyun，上传中文名文件，正常上传。

但是 carrierwave 1在ruby 3  + rails 6.1 下无法正常运行，于是我更新到 carrierwave 2 版本，就出现如上错误了。

**Comment by huacnlee** [comment]
看我增加的测试，中文文件名是没有问题的

**Comment by clwy-ito** [comment]
我看了你的测试文件，发现这里是直接调用了aliyun的sdk做了上传测试。
我也试过阿里云的sdk，是可以正常上传中文名文件的。

我经过进一步的检查源码。

### 尝试一：

```ruby
# carrierwave-aliyun/lib/carrierwave/aliyun/bucket.rb
def copy_object(source, dest)
        source = source.sub(PATH_PREFIX, "")
        dest = dest.sub(PATH_PREFIX, "")
        
       p source
       p dest
        
        oss_upload_client.copy_object(source, dest)
end
```

![image](https://user-images.githubusercontent.com/76093713/104896339-f043f100-59b1-11eb-9f40-8204df4836ce.png)

上传中文名字文件，可以看到source，变成了：`uploads/tmp/1610961807-902605656991249-0002-5702/%E4%B8%AD%E6%96%87.jpg`

猜测这个地方，中文名文件出错了


### 尝试二：

我检查了阿里云oss，发现上面生成了uploads/tmp目录

![image](https://user-images.githubusercontent.com/76093713/104900255-d2c55600-59b6-11eb-8c12-e3a421b01fe7.png)

![image](https://user-images.githubusercontent.com/76093713/104900360-f25c7e80-59b6-11eb-9d51-c6547d0c2047.png)

于是我将这里代码的路径写死，再次做了测试

```ruby
      def copy_object(source, dest)
        source = source.sub(PATH_PREFIX, "")
        dest = dest.sub(PATH_PREFIX, "")

        source = "uploads/tmp/1610963334-260916920551435-0002-7039/%E6%96%B0%E4%B8%AD%E6%96%87.jpg " # 失败了
        # source = "uploads/tmp/新中文.jpg" # 成功了
        dest = "uploads/2021/2faebb52-ddf8-45c9-8647-c89d0588117f.jpg"

        oss_upload_client.copy_object(source, dest)
      end
```

- 如果是正常中文名，是成功的。
- 使用carrierwave-aliyun上传后，文件名变成了`%E6%96%B0%E4%B8%AD%E6%96%87.jpg`的文件，再调用`oss_upload_client.copy_object`就执行失败了。

**Comment by clwy-ito** [comment]
如果可以的话，真的麻烦你，`git clone https://github.com/clwy-ito/demo`
实际执行以下看看，拜托了。
里面只有最基础的carrierwave + carrierwave-aliyun调用代码，没有任何多余的业务逻辑。

**Comment by huacnlee** [comment]
Version 1.2.2 has been fixed this issue.

**Comment by clwy-ito** [comment]
完美！
